### ISSUE TITLE
font issue?

### ISSUE THREAD

**Issue by kalekume** [ZOSOpenTools/powerline-goport#4]
I get this prompt using powerlinego:

�$�������_)�$�������_)�=��$�_)�$�������_)�b��$�_)�

seems to be a problem with the font. Any idea how to fix it?

**Comment by v1gnesh** [comment]
From powerline-go's readme:
> powerline-go uses ANSI color codes, these should nowadays work everywhere, but you may have to set your $TERM to xterm-256color for it to work.

Which terminal are you using; can you confirm if the above is set, relaunch & try again?

**Comment by kalekume** [comment]
thanks for the quick answer,

I set $TERM to xterm-256color but still same issue


<img width="983" alt="Screenshot 2024-05-15 081746" src="https://github.com/ZOSOpenTools/powerlinegoport/assets/63711967/67fee088-9620-4f21-8c26-9344512cca48">

**Comment by kalekume** [comment]
Hi,

I have changed bash shell to the ZOSOpenTools port and now it looks much better.  😀😀

![image](https://github.com/ZOSOpenTools/powerlinegoport/assets/63711967/340289e2-a074-4cd6-adb3-6e19b75ec7f7)
